export default function Cgu({ isDarkMode }: { isDarkMode: boolean }) {
    return (
        <div className={`w-full min-h-screen mx-auto p-6 shadow-lg ${isDarkMode ? "bg-dark-primary text-white" : "bg-light-primary text-black"} flex justify-center pt-40`}>
            <section className="max-w-3xl mx-auto px-4">
                <h1 className={`text-2xl font-bold text-center mb-4 font-title ${isDarkMode ? "text-white" : "text-black"}`}>Conditions générales d'utilisation</h1>
                <p className={`text-lg font-content leading-relaxed ${isDarkMode ? "text-white" : "text-black"}`}>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo libero recusandae quia eligendi ut vel, fuga blanditiis odit, autem porro officiis. Animi repudiandae labore facere, maxime totam distinctio magnam.
                    <br /><br />
                    Libero consectetur numquam sunt rem, culpa, iure voluptatem praesentium pariatur debitis, sit quo? Voluptate modi perspiciatis tempora dolorem ea, molestiae totam id pariatur sapiente repudiandae natus iusto facilis veniam quis tenetur hic, itaque numquam inventore, sed quisquam reiciendis illum in quaerat.
                    <br /><br />
                    Repellat fuga praesentium cum nobis mollitia adipisci totam. Facilis rem eum similique.
                    <br />
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed omnis est delectus! Vitae, animi, sed recusandae nisi obcaecati dicta minus facilis corporis iusto facere quisquam officia consectetur ipsa rerum! Vero, quaerat officia sunt tempore magni quae! Earum beatae iusto obcaecati rerum, sint molestias non sapiente voluptas sed id magni atque quidem facilis nulla corporis voluptatibus recusandae perferendis illo maxime aut? Doloremque dolorem placeat vitae esse ut, aperiam voluptatem soluta enim asperiores earum illo consequuntur harum vel accusamus corrupti. Cum, molestias velit nobis esse ad ratione repudiandae dolore consequuntur asperiores! Perspiciatis, enim ipsam saepe sint maxime, sapiente in delectus porro reiciendis, vel cum! Sed, aut nesciunt. Voluptates repellat expedita incidunt et laboriosam vitae officia odit, quas amet ad tempore dolorum cupiditate debitis sed soluta totam, eius ipsam obcaecati, iure fugit numquam omnis odio. Repellendus illo reprehenderit atque aliquam minus? Earum autem sit commodi eligendi culpa. Nesciunt, debitis libero. Ipsum numquam expedita enim deserunt itaque accusamus aperiam voluptatum doloremque distinctio optio doloribus illum, molestias eligendi voluptas, tenetur, inventore odit. Quis ad hic, commodi eius at culpa facilis sed, architecto vel unde ipsam repudiandae vitae in nostrum amet rem excepturi consequatur voluptas ducimus voluptatem maiores, quidem inventore suscipit. Autem earum ipsam voluptas vel dignissimos, inventore id reprehenderit saepe impedit eius quibusdam! Architecto in reprehenderit rerum nisi, blanditiis iste similique excepturi asperiores esse. Velit nobis dignissimos accusamus, earum aut sit, exercitationem hic fuga nesciunt id nihil quibusdam quis magnam, neque fugit temporibus aliquam quidem dolorem. Quae eligendi animi aut molestiae quo mollitia sapiente reiciendis corporis accusantium, in voluptatibus quas minus dignissimos velit sint perspiciatis qui aspernatur. Distinctio unde quod rerum nihil necessitatibus quis deleniti nam reprehenderit. Reprehenderit neque sequi eaque dicta repellat. Voluptates consectetur ea, accusamus sed nesciunt doloremque! Quod ex laborum obcaecati exercitationem modi. Eveniet officiis ea, recusandae eius eligendi ullam? Sed, voluptatibus!
                </p>
            </section>
        </div>
    );
}
